url: 'http://fngryboi.github.io'
domain_name: 'http://fngryboi.github.io/'

# variables
name: Fngryboi's PC
title: Fngryboi's PC
description: Development Shenanigans, Gaming, Modding, VR.
google_verification: null

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true

# General Jekyll Config
lsi: false
include: [".htaccess"]
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]